#!/bin/bash
set -e

# this needs to be fixed TODO
# - pull loader and clis using npx 
# - npx create project is based on the project repo 
# - pm2-runtime will be used only if installed
# - pm2-runtime will be installed if not available in cache


# try things both ways since it more than likely won't cause us problems
if [[ "${1#-}" != "${1}" ]]; then
	
  lyns -c "pm2-runtime $@"
  lyns -c "$*"
fi

if [[ "${1}" == "pm2" ]]; then
   lyns -c "pm2-runtime $*"
fi

if [[ "${1}" == "fish" ]]; then
  lyns -c "$*"
fi
 