
LYNS_STATICCHAR_PREFIX="${LYNS_STATICCHAR_PREFIX=""}"
LYNS_STATICCHAR_SUFFIX="${LYNS_STATICCHAR_SUFFIX=""}"
LYNS_STATICCHAR_SYMBOL="${LYNS_STATICCHAR_SYMBOL="➜ "}"
LYNS_STATICCHAR_SYMBOL_ROOT="${LYNS_STATICCHAR_SYMBOL_ROOT="$LYNS_STATICCHAR_SYMBOL"}"
LYNS_STATICCHAR_SYMBOL_SECONDARY="${LYNS_STATICCHAR_SYMBOL_SECONDARY="$LYNS_STATICCHAR_SYMBOL"}"
LYNS_STATICCHAR_COLOR_SUCCESS="${LYNS_STATICCHAR_COLOR_SUCCESS="green"}"
LYNS_STATICCHAR_COLOR_FAILURE="${LYNS_STATICCHAR_COLOR_FAILURE="red"}"
LYNS_STATICCHAR_COLOR_SECONDARY="${LYNS_STATICCHAR_COLOR_SECONDARY="yellow"}"

_lyns_char() {
  local 'color' 'char'

  if [[ $RETVAL -eq 0 ]]; then
    color="$LYNS_STATICCHAR_COLOR_SUCCESS"
  else
    color="$LYNS_STATICCHAR_COLOR_FAILURE"
  fi

  if [[ $UID -eq 0 ]]; then
    char="$LYNS_STATICCHAR_SYMBOL_ROOT"
  else
    char="$LYNS_STATICCHAR_SYMBOL"
  fi

  asyncs::section \
    "$color" \
    "$LYNS_STATICCHAR_PREFIX" \
    "$char" \
    "$LYNS_STATICCHAR_SUFFIX"
}
