
LYNS_STATICEXEC_TIME_SHOW="${LYNS_STATICEXEC_TIME_SHOW=true}"
LYNS_STATICEXEC_TIME_PREFIX="${LYNS_STATICEXEC_TIME_PREFIX="took "}"
LYNS_STATICEXEC_TIME_SUFFIX="${LYNS_STATICEXEC_TIME_SUFFIX="$LYNS_QUERY_DEFAULT_SUFFIX"}"
LYNS_STATICEXEC_TIME_COLOR="${LYNS_STATICEXEC_TIME_COLOR="yellow"}"
LYNS_STATICEXEC_TIME_ELAPSED="${LYNS_STATICEXEC_TIME_ELAPSED=2}"

_lyns_exec_time() {
  [[ $LYNS_STATICEXEC_TIME_SHOW == false ]] && return

  if [[ $LYNS_STATICEXEC_TIME_duration -ge $LYNS_STATICEXEC_TIME_ELAPSED ]]; then
    asyncs::section \
      "$LYNS_STATICEXEC_TIME_COLOR" \
      "$LYNS_STATICEXEC_TIME_PREFIX" \
      "$(asyncs::displaytime $LYNS_STATICEXEC_TIME_duration)" \
      "$LYNS_STATICEXEC_TIME_SUFFIX"
  fi
}
