








LYNS_STATICEXIT_CODE_SHOW="${LYNS_STATICEXIT_CODE_SHOW=false}"
LYNS_STATICEXIT_CODE_PREFIX="${LYNS_STATICEXIT_CODE_PREFIX=""}"
LYNS_STATICEXIT_CODE_SUFFIX="${LYNS_STATICEXIT_CODE_SUFFIX=" "}"
LYNS_STATICEXIT_CODE_SYMBOL="${LYNS_STATICEXIT_CODE_SYMBOL="✘"}"
LYNS_STATICEXIT_CODE_COLOR="${LYNS_STATICEXIT_CODE_COLOR="red"}"





_lyns_exit_code() {
  [[ $LYNS_STATICEXIT_CODE_SHOW == false || $RETVAL == 0 ]] && return

  asyncs::section \
    "$LYNS_STATICEXIT_CODE_COLOR" \
    "$LYNS_STATICEXIT_CODE_PREFIX" \
    "${LYNS_STATICEXIT_CODE_SYMBOL}$RETVAL" \
    "$LYNS_STATICEXIT_CODE_SUFFIX"
}
