
LYNS_STATICGCLOUD_SHOW="${LYNS_STATICGCLOUD_SHOW=true}"
LYNS_STATICGCLOUD_PREFIX="${LYNS_STATICGCLOUD_PREFIX="using "}"
LYNS_STATICGCLOUD_SUFFIX="${LYNS_STATICGCLOUD_SUFFIX="$LYNS_QUERY_DEFAULT_SUFFIX"}"
LYNS_STATICGCLOUD_SYMBOL="${LYNS_STATICGCLOUD_SYMBOL="☁️  "}"
LYNS_STATICGCLOUD_COLOR="${LYNS_STATICGCLOUD_COLOR="26"}"

_lyns_gcloud() {
  [[ $LYNS_STATICGCLOUD_SHOW == false ]] && return

  asyncs::exists gcloud || return  
  local GCLOUD_DIR=${HOME}/.config/gcloud/
  [[ -f ${GCLOUD_DIR}/active_config ]] || return
  
  if (( ${+CLOUDSDK_ACTIVE_CONFIG_NAME} )); then
    
    local GCLOUD_ACTIVE_CONFIG=${CLOUDSDK_ACTIVE_CONFIG_NAME}
  else
    
    local GCLOUD_ACTIVE_CONFIG=$(head -n1 ${GCLOUD_DIR}/active_config)
  fi

  
  local GCLOUD_ACTIVE_CONFIG_FILE=${GCLOUD_DIR}/configurations/config_${GCLOUD_ACTIVE_CONFIG}
  [[ -f ${GCLOUD_ACTIVE_CONFIG_FILE} ]] || return

  local GCLOUD_ACTIVE_PROJECT=$(sed -n 's/project = \(.*\)/\1/p' ${GCLOUD_ACTIVE_CONFIG_FILE})

  
  LYNS_STATICGCLOUD_TEXT="${GCLOUD_ACTIVE_CONFIG}/${GCLOUD_ACTIVE_PROJECT}"
  asyncs::section \
    "$LYNS_STATICGCLOUD_COLOR" \
    "$LYNS_STATICGCLOUD_PREFIX" \
    "${LYNS_STATICGCLOUD_SYMBOL}${LYNS_STATICGCLOUD_TEXT}" \
    "$LYNS_STATICGCLOUD_SUFFIX"
}
