
LYNS_STATICJOBS_SHOW="${LYNS_STATICJOBS_SHOW=true}"
LYNS_STATICJOBS_PREFIX="${LYNS_STATICJOBS_PREFIX=""}"
LYNS_STATICJOBS_SUFFIX="${LYNS_STATICJOBS_SUFFIX=" "}"
LYNS_STATICJOBS_SYMBOL="${LYNS_STATICJOBS_SYMBOL="✦"}"
LYNS_STATICJOBS_COLOR="${LYNS_STATICJOBS_COLOR="blue"}"
LYNS_STATICJOBS_AMOUNT_PREFIX="${LYNS_STATICJOBS_AMOUNT_PREFIX=""}"
LYNS_STATICJOBS_AMOUNT_SUFFIX="${LYNS_STATICJOBS_AMOUNT_SUFFIX=""}"
LYNS_STATICJOBS_AMOUNT_THRESHOLD="${LYNS_STATICJOBS_AMOUNT_THRESHOLD=1}"

_lyns_jobs() {
  [[ $LYNS_STATICJOBS_SHOW == false ]] && return

  local jobs_amount=$( jobs -d | awk '!/pwd/' | wc -l | tr -d " ")

  [[ $jobs_amount -gt 0 ]] || return

  if [[ $jobs_amount -le $LYNS_STATICJOBS_AMOUNT_THRESHOLD ]]; then
    jobs_amount=''
    LYNS_STATICJOBS_AMOUNT_PREFIX=''
    LYNS_STATICJOBS_AMOUNT_SUFFIX=''
  fi

  asyncs::section \
    "$LYNS_STATICJOBS_COLOR" \
    "$LYNS_STATICJOBS_PREFIX" \
    "${LYNS_STATICJOBS_SYMBOL}${LYNS_STATICJOBS_AMOUNT_PREFIX}${jobs_amount}${LYNS_STATICJOBS_AMOUNT_SUFFIX}" \
    "$LYNS_STATICJOBS_SUFFIX"
}
