
LYNS_STATICVENV_SHOW="${LYNS_STATICVENV_SHOW=true}"
LYNS_STATICVENV_PREFIX="${LYNS_STATICVENV_PREFIX="$LYNS_QUERY_DEFAULT_PREFIX"}"
LYNS_STATICVENV_SUFFIX="${LYNS_STATICVENV_SUFFIX="$LYNS_QUERY_DEFAULT_SUFFIX"}"
LYNS_STATICVENV_SYMBOL="${LYNS_STATICVENV_SYMBOL=""}"

LYNS_STATICVENV_GENERIC_NAMES="${(A)=LYNS_STATICVENV_GENERIC_NAMES=virtualenv venv .venv}"
LYNS_STATICVENV_COLOR="${LYNS_STATICVENV_COLOR="blue"}"

_lyns_venv() {
  [[ $LYNS_STATICVENV_SHOW == false ]] && return

  
  [ -n "$VIRTUAL_ENV" ] || return

  local 'venv'

  if [[ "${LYNS_STATICVENV_GENERIC_NAMES[(i)$VIRTUAL_ENV:t]}" -le \
        "${
  then
    venv="$VIRTUAL_ENV:h:t"
  else
    venv="$VIRTUAL_ENV:t"
  fi

asyncs::section \
    "$LYNS_STATICVENV_COLOR" \
    "$LYNS_STATICVENV_PREFIX" \
    "${LYNS_STATICVENV_SYMBOL}${venv}" \
    "$LYNS_STATICVENV_SUFFIX"
}
